"""Production scaffold builder."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from rebot.auto.spec_compiler import SpecSchema
from rebot.auto.arch_synthesizer import ArchitectureSchema
from rebot.auto.ui_designer import UIDesignSchema
from rebot.auto.desktop_scaffold import build_electron_app


@dataclass
class ProductionBuilder:
    root: Path

    def build(
        self,
        spec: SpecSchema,
        arch: ArchitectureSchema,
        *,
        language: str,
        ui: UIDesignSchema | None = None,
        scaffold: bool = True,
    ) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        (self.root / "docs").mkdir(exist_ok=True)
        (self.root / "backend").mkdir(exist_ok=True)
        (self.root / "frontend").mkdir(exist_ok=True)
        (self.root / "mobile").mkdir(exist_ok=True)
        (self.root / "desktop").mkdir(exist_ok=True)
        (self.root / "miniapp").mkdir(exist_ok=True)
        (self.root / "infra").mkdir(exist_ok=True)

        (self.root / "docs" / "SPEC.json").write_text(spec.model_dump_json(), encoding="utf-8")
        (self.root / "docs" / "ARCH.json").write_text(arch.model_dump_json(), encoding="utf-8")
        if ui is not None:
            (self.root / "docs" / "UI.json").write_text(ui.model_dump_json(), encoding="utf-8")
        (self.root / "README.md").write_text(
            f"# {spec.product}\n\nGenerated by Rebot.\n", encoding="utf-8"
        )

        if scaffold:
            if language.lower() == "python":
                (self.root / "backend" / "app.py").write_text(
                    "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/health')\ndef health():\n    return {'ok': True}\n",
                    encoding="utf-8",
                )
                (self.root / "backend" / "requirements.txt").write_text(
                    "fastapi\nuvicorn\n", encoding="utf-8"
                )
            elif language.lower() in {"ts", "typescript", "node"}:
                (self.root / "backend" / "index.ts").write_text(
                    "import express from 'express';\nconst app = express();\n", encoding="utf-8"
                )

            (self.root / "frontend" / "README.md").write_text(
                _render_frontend_readme(spec.product), encoding="utf-8"
            )
            (self.root / "frontend" / "src").mkdir(parents=True, exist_ok=True)
            (self.root / "frontend" / "src" / "main.jsx").write_text(
                _render_web_main(),
                encoding="utf-8",
            )
            (self.root / "frontend" / "src" / "App.jsx").write_text(
                _render_web_workbench(spec.product, ui),
                encoding="utf-8",
            )
            (self.root / "frontend" / "src" / "styles.css").write_text(
                _render_web_styles(ui) + "\n" + _render_workbench_styles(),
                encoding="utf-8",
            )
            (self.root / "frontend" / "index.html").write_text(
                _render_web_index(spec.product),
                encoding="utf-8",
            )
            (self.root / "frontend" / "package.json").write_text(
                _render_web_package_json(spec.product),
                encoding="utf-8",
            )
            (self.root / "frontend" / "vite.config.js").write_text(
                _render_vite_config(),
                encoding="utf-8",
            )
            build_electron_app(self.root / "desktop" / "electron", spec.product)
            _build_ios_app(self.root / "mobile" / "ios", spec.product, ui)
            _build_expo_app(self.root / "mobile" / "expo", spec.product, ui)
            (self.root / "miniapp" / "README.md").write_text(
                "Mini-program scaffold placeholder.\n", encoding="utf-8"
            )
            _build_wechat_miniapp(self.root / "miniapp" / "wechat", spec.product, ui)
        if scaffold:
            (self.root / "infra" / "Dockerfile").write_text(
                "FROM python:3.11-slim\nWORKDIR /app\nCOPY backend /app/backend\n",
                encoding="utf-8",
            )
            (self.root / "infra" / "docker-compose.yml").write_text(
                "version: '3'\nservices:\n  backend:\n    build: .\n    ports: ['8000:8000']\n",
                encoding="utf-8",
            )


def _render_swiftui_theme(ui: UIDesignSchema | None) -> str:
    if ui is None:
        return "import SwiftUI\n\nstruct Theme { static let primary = Color.blue }\n"
    primary = ui.colors.get("primary", "#16A34A")
    bg = ui.colors.get("background", "#F6F7FB")
    accent = ui.colors.get("accent", "#0EA5E9")
    return (
        "import SwiftUI\n\n"
        "struct Theme {\n"
        f"  static let primary = Color(\"{primary}\")\n"
        f"  static let background = Color(\"{bg}\")\n"
        f"  static let accent = Color(\"{accent}\")\n"
        "}\n"
    )


def _render_home_view(product: str, ui: UIDesignSchema | None) -> str:
    title = product or "Smart App"
    spacing = 16
    if ui and ui.spacing.get("md"):
        spacing = int(ui.spacing.get("md", 16))
    return (
        "import SwiftUI\n\n"
        "struct HomeView: View {\n"
        "  var body: some View {\n"
        f"    VStack(spacing: {spacing}) {{\n"
        f"      Text(\"{title}\").font(.largeTitle).bold()\n"
        "      Text(\"Today\\'s focus\").font(.headline)\n"
        "      RoundedRectangle(cornerRadius: 18).fill(Theme.primary.opacity(0.15)).frame(height: 140)\n"
        "      RoundedRectangle(cornerRadius: 18).fill(Theme.accent.opacity(0.12)).frame(height: 100)\n"
        "      Button(action: {}) { Text(\"Get Started\").padding().background(Theme.primary).foregroundColor(.white).cornerRadius(12) }\n"
        "    }.padding(24).background(Theme.background)\n"
        "  }\n"
        "}\n"
    )


def _build_ios_app(path: Path, product: str, ui: UIDesignSchema | None) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "README.md").write_text(
        "SwiftUI scaffold. Open in Xcode and create a new iOS App, then replace files.\n",
        encoding="utf-8",
    )
    (path / "Theme.swift").write_text(_render_swiftui_theme(ui), encoding="utf-8")
    (path / "HomeView.swift").write_text(
        _render_home_view(product, ui),
        encoding="utf-8",
    )
    (path / "AppMain.swift").write_text(
        "import SwiftUI\n\n@main\nstruct AppMain: App { var body: some Scene { WindowGroup { HomeView() } } }\n",
        encoding="utf-8",
    )


def _build_expo_app(path: Path, product: str, ui: UIDesignSchema | None) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "package.json").write_text(_render_expo_package_json(product), encoding="utf-8")
    (path / "app.json").write_text(_render_expo_app_json(product), encoding="utf-8")
    (path / "App.tsx").write_text(_render_expo_app(product, ui), encoding="utf-8")
    (path / "tsconfig.json").write_text(
        "{\n  \"extends\": \"expo/tsconfig.base\"\n}\n", encoding="utf-8"
    )
    (path / "babel.config.js").write_text(
        "module.exports = function(api) { api.cache(true); return { presets: ['babel-preset-expo'] }; };\n",
        encoding="utf-8",
    )


def _render_expo_package_json(product: str) -> str:
    name = product.lower().replace(" ", "-")
    return (
        "{\n"
        f"  \"name\": \"{name}\",\n"
        "  \"version\": \"1.0.0\",\n"
        "  \"main\": \"node_modules/expo/AppEntry.js\",\n"
        "  \"scripts\": {\n"
        "    \"start\": \"expo start\",\n"
        "    \"android\": \"expo start --android\",\n"
        "    \"ios\": \"expo start --ios\",\n"
        "    \"web\": \"expo start --web\"\n"
        "  },\n"
        "  \"dependencies\": {\n"
        "    \"expo\": \"~50.0.6\",\n"
        "    \"react\": \"18.2.0\",\n"
        "    \"react-native\": \"0.73.2\"\n"
        "  },\n"
        "  \"devDependencies\": {\n"
        "    \"@types/react\": \"~18.2.45\",\n"
        "    \"typescript\": \"^5.3.3\"\n"
        "  },\n"
        "  \"private\": true\n"
        "}\n"
    )


def _render_expo_app_json(product: str) -> str:
    return (
        "{\n"
        "  \"expo\": {\n"
        f"    \"name\": \"{product}\",\n"
        f"    \"slug\": \"{product.lower().replace(' ', '-')}\",\n"
        "    \"version\": \"1.0.0\",\n"
        "    \"orientation\": \"portrait\",\n"
        "    \"platforms\": [\"ios\", \"android\", \"web\"],\n"
        "    \"sdkVersion\": \"50.0.0\"\n"
        "  }\n"
        "}\n"
    )


def _render_expo_app(product: str, ui: UIDesignSchema | None) -> str:
    colors = ui.colors if ui else {}
    primary = colors.get("primary", "#0F172A")
    accent = colors.get("accent", "#0EA5E9")
    background = colors.get("background", "#F8FAFC")
    return (
        "import { StatusBar } from 'expo-status-bar'\n"
        "import { StyleSheet, Text, View, Pressable } from 'react-native'\n\n"
        "export default function App() {\n"
        "  return (\n"
        "    <View style={styles.container}>\n"
        f"      <Text style={styles.title}>{product}</Text>\n"
        "      <Text style={styles.subtitle}>One-shot generated mobile experience</Text>\n"
        "      <View style={styles.card} />\n"
        "      <Pressable style={styles.button}>\n"
        "        <Text style={styles.buttonText}>Get started</Text>\n"
        "      </Pressable>\n"
        "      <StatusBar style=\"dark\" />\n"
        "    </View>\n"
        "  )\n"
        "}\n\n"
        "const styles = StyleSheet.create({\n"
        f"  container: {{ flex: 1, backgroundColor: '{background}', padding: 28, justifyContent: 'center' }},\n"
        "  title: { fontSize: 32, fontWeight: '700', marginBottom: 8 },\n"
        "  subtitle: { opacity: 0.7, marginBottom: 20 },\n"
        f"  card: {{ height: 140, borderRadius: 18, backgroundColor: '{accent}', opacity: 0.15, marginBottom: 20 }},\n"
        f"  button: {{ backgroundColor: '{primary}', paddingVertical: 14, paddingHorizontal: 24, borderRadius: 999 }},\n"
        "  buttonText: { color: '#fff', fontWeight: '600', textAlign: 'center' }\n"
        "})\n"
    )


def _build_wechat_miniapp(path: Path, product: str, ui: UIDesignSchema | None) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "app.js").write_text("App({})\n", encoding="utf-8")
    (path / "app.json").write_text(
        "{\n  \"pages\": [\"pages/index/index\"],\n  \"window\": {\"navigationBarTitleText\": \""
        + product
        + "\"}\n}\n",
        encoding="utf-8",
    )
    (path / "app.wxss").write_text("page { background: #f7f7fb; }\n", encoding="utf-8")
    pages = path / "pages" / "index"
    pages.mkdir(parents=True, exist_ok=True)
    (pages / "index.wxml").write_text(
        "<view class=\"page\">\n  <view class=\"title\">" + product + "</view>\n  <view class=\"card\"></view>\n  <button class=\"cta\">Get started</button>\n</view>\n",
        encoding="utf-8",
    )
    (pages / "index.js").write_text("Page({})\n", encoding="utf-8")
    (pages / "index.json").write_text("{\"usingComponents\":{}}\n", encoding="utf-8")
    (pages / "index.wxss").write_text(
        ".page { padding: 24rpx; }\n.title { font-size: 40rpx; font-weight: 600; margin-bottom: 24rpx; }\n.card { height: 240rpx; border-radius: 24rpx; background: rgba(14,165,233,0.12); margin-bottom: 24rpx; }\n.cta { background: #0f172a; color: #fff; border-radius: 999rpx; }\n",
        encoding="utf-8",
    )


def _render_frontend_readme(product: str) -> str:
    return (
        f"# {product} Web UI\n\n"
        "This folder contains a runnable Vite + React UI.\n\n"
        "Quick start:\n"
        "1. npm install\n"
        "2. npm run dev\n\n"
        "Agent console notes:\n"
        "- Update API key and workspace in `src/App.jsx` before running.\n"
        "- Workspace path can be typed in the UI; for desktop apps, wire it to a native folder picker.\n"
        "- Editor supports file search, JSON format, and diff view.\n"
        "- WebSocket events are read from `/ws/events` on the same host.\n\n"
        "- `index.html` and `src/main.jsx` are Vite entry points.\n"
        "- `src/App.jsx` and `src/styles.css` are the main editable sources.\n"
    )


def _render_web_index(product: str) -> str:
    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\" />\n"
        f"  <title>{product} UI Preview</title>\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "</head>\n"
        "<body>\n"
        "  <div id=\"root\"></div>\n"
        "  <script type=\"module\" src=\"/src/main.jsx\"></script>\n"
        "</body>\n"
        "</html>\n"
    )


def _render_web_workbench(product: str, ui: UIDesignSchema | None) -> str:
    pages = ui.pages if ui else ["Home", "Explore", "Insights", "Profile"]
    task_items = "\n".join(
        f"          <li><span className=\"dot\"></span>{page} flow</li>" for page in pages[:6]
    )
    return (
        "import './styles.css'\n"
        "import { useMemo, useState } from 'react'\n"
        "import Editor from '@monaco-editor/react'\n\n"
        "export default function App() {\n"
        "  const [prompt, setPrompt] = useState('Build a fitness iOS app with a streak system.')\n"
        "  const [events, setEvents] = useState([])\n"
        "  const [toolCalls, setToolCalls] = useState([])\n"
        "  const [runId, setRunId] = useState(null)\n"
        "  const [tasks, setTasks] = useState(['Spec compile', 'Architecture', 'UI layout', 'Codegen'])\n"
        "  const [workspace, setWorkspace] = useState('C:/workspace/project')\n"
        "  const [files, setFiles] = useState([])\n"
        "  const [activeFile, setActiveFile] = useState({ path: '', language: 'plaintext', content: '' })\n"
        "  const [originalContent, setOriginalContent] = useState('')\n"
        "  const [search, setSearch] = useState('')\n"
        "  const [showDiff, setShowDiff] = useState(false)\n"
        "  const [status, setStatus] = useState('idle')\n"
        "  const [previewUrl, setPreviewUrl] = useState('http://localhost:5173')\n"
        "  const [previewInput, setPreviewInput] = useState('http://localhost:5173')\n"
        "  const [securityRun, setSecurityRun] = useState(null)\n"
        "  const wsUrl = useMemo(() => {\n"
        "    const host = window.location.host\n"
        "    const proto = window.location.protocol === 'https:' ? 'wss' : 'ws'\n"
        "    return `${proto}://${host}/ws/events`\n"
        "  }, [])\n\n"
        "  function handleExecute() {\n"
        "    setStatus('running')\n"
        "    fetch('/api/execute', {\n"
        "      method: 'POST',\n"
        "      headers: { 'Content-Type': 'application/json' },\n"
        "      body: JSON.stringify({\n"
        "        task: prompt,\n"
        "        api_key: 'YOUR_API_KEY',\n"
        "        model: 'gpt-4o-mini',\n"
        "        base_url: 'https://api.openai.com/v1',\n"
        "        workspace\n"
        "      })\n"
        "    })\n"
        "      .then(res => res.json())\n"
        "      .then(data => {\n"
        "        setRunId(data.run_id)\n"
        "        subscribeEvents(data.run_id)\n"
        "      })\n"
        "  }\n\n"
        "  function subscribeEvents(targetRunId) {\n"
        "    const socket = new WebSocket(wsUrl)\n"
        "    socket.onmessage = (event) => {\n"
        "      const batch = JSON.parse(event.data)\n"
        "      if (batch.run_id && targetRunId && batch.run_id !== targetRunId) return\n"
        "      const list = batch.events || []\n"
        "      setEvents(prev => [...list.reverse(), ...prev].slice(0, 200))\n"
        "      list.forEach((payload) => {\n"
        "        if (payload.type === 'tool_call') {\n"
        "          setToolCalls(prev => [payload.payload, ...prev].slice(0, 50))\n"
        "        }\n"
        "        if (payload.type === 'tool_start') {\n"
        "          setToolCalls(prev => [{ name: payload.name, args: payload.payload }, ...prev].slice(0, 50))\n"
        "        }\n"
        "        if (payload.type === 'tool_end') {\n"
        "          setToolCalls(prev => [{ name: payload.name, args: payload.payload }, ...prev].slice(0, 50))\n"
        "        }\n"
        "      })\n"
        "    }\n"
        "    socket.onclose = () => setStatus('idle')\n"
        "  }\n\n"
        "  return (\n"
        "    <div className=\"workbench\">\n"
        "      <header className=\"wb-top\">\n"
        f"        <div className=\"brand\">{product} Agent Studio</div>\n"
        "        <div className={`status ${status}`}>{status}</div>\n"
        "      </header>\n"
        "      <section className=\"wb-body\">\n"
        "        <aside className=\"wb-left\">\n"
        "          <div className=\"panel-title\">AI Tasks</div>\n"
        "          <div className=\"task-tree\">\n"
        "            <ul>\n"
        f"{task_items}\n"
        "            </ul>\n"
        "          </div>\n"
        "          <div className=\"panel-title\">Tools</div>\n"
        "          <div className=\"tool-list\">\n"
        "            {toolCalls.length === 0 ? <div className=\"empty\">No tool calls yet.</div> : null}\n"
        "            {toolCalls.map((t, idx) => (\n"
        "              <div key={idx} className=\"tool-call\">\n"
        "                <div className=\"tool-name\">{t.name || 'tool'}</div>\n"
        "                <div className=\"tool-args\">{JSON.stringify(t.args || {})}</div>\n"
        "              </div>\n"
        "            ))}\n"
        "          </div>\n"
        "        </aside>\n"
        "        <main className=\"wb-center\">\n"
        "          <div className=\"panel-title\">Prompt</div>\n"
        "          <textarea value={prompt} onChange={e => setPrompt(e.target.value)} />\n"
        "          <div className=\"actions\">\n"
        "            <button className=\"cta\" onClick={handleExecute}>Run Agent</button>\n"
        "            <button className=\"ghost\" onClick={loadWorkspace}>Load Files</button>\n"
        "          </div>\n"
        "          <div className=\"panel-title\">Workspace</div>\n"
        "          <div className=\"workspace-input\">\n"
        "            <input value={workspace} onChange={e => setWorkspace(e.target.value)} placeholder=\"Workspace path\" />\n"
        "            <button className=\"ghost\" onClick={chooseWorkspace}>Choose</button>\n"
        "            <button className=\"ghost\" onClick={saveFile}>Save File</button>\n"
        "            <button className=\"ghost\" onClick={formatContent}>Format</button>\n"
        "            <button className=\"ghost\" onClick={() => setShowDiff(!showDiff)}>Diff</button>\n"
        "          </div>\n"
        "          <div className=\"panel-title\">Workspace</div>\n"
        "          <div className=\"editor-shell\">\n"
        "            <div className=\"file-tree\">\n"
        "              <input className=\"file-search\" placeholder=\"Search files\" value={search} onChange={e => setSearch(e.target.value)} />\n"
        "              {files.map((f, idx) => (\n"
        "                !search || f.toLowerCase().includes(search.toLowerCase()) ? (\n"
        "                <button\n"
        "                  key={idx}\n"
        "                  className={`file-item ${activeFile.path === f ? 'active' : ''}`}\n"
        "                  onClick={() => openFile(f)}\n"
        "                >\n"
        "                  {f}\n"
        "                </button>\n"
        "                ) : null\n"
        "              ))}\n"
        "            </div>\n"
        "            <div className=\"editor-pane\">\n"
        "              <div className=\"editor-header\">{activeFile.path}</div>\n"
        "              {showDiff ? (\n"
        "                <pre className=\"diff-view\">{diffLines()}</pre>\n"
        "              ) : (\n"
        "                <Editor\n"
        "                  height=\"360px\"\n"
        "                  language={activeFile.language}\n"
        "                  value={activeFile.content}\n"
        "                  onChange={(value) => setActiveFile(prev => ({ ...prev, content: value || '' }))}\n"
        "                  theme=\"vs-dark\"\n"
        "                  options={{ minimap: { enabled: false }, fontSize: 13 }}\n"
        "                />\n"
        "              )}\n"
        "            </div>\n"
        "          </div>\n"
        "        </main>\n"
        "        <aside className=\"wb-right\">\n"
        "          <div className=\"panel-title\">Preview</div>\n"
        "          <div className=\"preview-controls\">\n"
        "            <button className=\"ghost\" onClick={() => { setPreviewUrl('http://localhost:5173'); setPreviewInput('http://localhost:5173'); }}>Web</button>\n"
        "            <button className=\"ghost\" onClick={() => { setPreviewUrl('http://localhost:19006'); setPreviewInput('http://localhost:19006'); }}>Expo Web</button>\n"
        "            <input className=\"preview-input\" value={previewInput} onChange={e => setPreviewInput(e.target.value)} placeholder=\"Preview URL\" />\n"
        "            <button className=\"ghost\" onClick={() => setPreviewUrl(previewInput)}>Go</button>\n"
        "            <button className=\"ghost\" onClick={runSecurityTest}>Run Security Test</button>\n"
        "          </div>\n"
        "          <div className=\"preview\">\n"
        "            <iframe title=\"preview\" src={previewUrl} />\n"
        "          </div>\n"
        "          <div className=\"panel-title\">WebSocket Events</div>\n"
        "          <div className=\"event-stream\">\n"
        "            {events.length === 0 ? <div className=\"empty\">No events yet.</div> : null}\n"
        "            {events.map((ev, idx) => (\n"
        "              <div key={idx} className=\"event\">\n"
        "                <div className=\"event-type\">{ev.type}</div>\n"
        "                <pre>{JSON.stringify(ev.payload || ev, null, 2)}</pre>\n"
        "              </div>\n"
        "            ))}\n"
        "          </div>\n"
        "        </aside>\n"
        "      </section>\n"
        "    </div>\n"
        "  )\n"
        "}\n"
    )


def _render_web_main() -> str:
    return (
        "import React from 'react'\n"
        "import { createRoot } from 'react-dom/client'\n"
        "import App from './App'\n\n"
        "const root = createRoot(document.getElementById('root'))\n"
        "root.render(<App />)\n"
    )


def _render_web_package_json(product: str) -> str:
    return (
        "{\n"
        f"  \"name\": \"{product.lower().replace(' ', '-')}\",\n"
        "  \"private\": true,\n"
        "  \"version\": \"0.1.0\",\n"
        "  \"type\": \"module\",\n"
        "  \"scripts\": {\n"
        "    \"dev\": \"vite\",\n"
        "    \"build\": \"vite build\",\n"
        "    \"preview\": \"vite preview\"\n"
        "  },\n"
        "  \"dependencies\": {\n"
        "    \"@monaco-editor/react\": \"^4.6.0\",\n"
        "    \"prettier\": \"^3.3.3\",\n"
        "    \"react\": \"^18.3.1\",\n"
        "    \"react-dom\": \"^18.3.1\"\n"
        "  },\n"
        "  \"devDependencies\": {\n"
        "    \"vite\": \"^5.4.8\"\n"
        "  }\n"
        "}\n"
    )


def _render_vite_config() -> str:
    return (
        "import { defineConfig } from 'vite'\n\n"
        "export default defineConfig({\n"
        "  server: {\n"
        "    port: 5173\n"
        "  }\n"
        "})\n"
    )


def _render_web_styles(ui: UIDesignSchema | None) -> str:
    colors = ui.colors if ui else {}
    typography = ui.typography if ui else {}
    spacing = ui.spacing if ui else {}
    radius = ui.radius if ui else {}
    primary = colors.get("primary", "#0F172A")
    accent = colors.get("accent", "#0EA5E9")
    background = colors.get("background", "#F8FAFC")
    surface = colors.get("surface", "#FFFFFF")
    text = colors.get("text", "#0F172A")
    font = typography.get("display", "Space Grotesk")
    body = typography.get("body", "Inter")
    gap = int(spacing.get("md", 16)) if spacing else 16
    card_radius = int(radius.get("lg", 20)) if radius else 20
    return (
        "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Space+Grotesk:wght@500;700&display=swap');\n"
        ":root {\n"
        f"  --primary: {primary};\n"
        f"  --accent: {accent};\n"
        f"  --bg: {background};\n"
        f"  --surface: {surface};\n"
        f"  --text: {text};\n"
        f"  --gap: {gap}px;\n"
        f"  --radius: {card_radius}px;\n"
        f"  --display-font: '{font}', sans-serif;\n"
        f"  --body-font: '{body}', sans-serif;\n"
        "}\n"
        "* { box-sizing: border-box; }\n"
        "body { margin: 0; background: var(--bg); color: var(--text); font-family: var(--body-font); }\n"
        ".app { padding: 48px 6vw 80px; display: flex; flex-direction: column; gap: 32px; }\n"
        ".hero { padding: 40px; border-radius: var(--radius); background: linear-gradient(135deg, rgba(15,23,42,0.05), rgba(14,165,233,0.18)); }\n"
        ".hero h1 { margin: 0 0 12px; font-family: var(--display-font); font-size: 48px; letter-spacing: -0.02em; }\n"
        ".hero p { margin: 0 0 24px; max-width: 520px; opacity: 0.8; }\n"
        ".cta-row { display: flex; gap: 12px; }\n"
        ".cta, .ghost { border: none; padding: 12px 22px; border-radius: 999px; font-weight: 600; cursor: pointer; }\n"
        ".cta { background: var(--primary); color: #fff; }\n"
        ".ghost { background: transparent; color: var(--primary); border: 1px solid rgba(15,23,42,0.2); }\n"
        ".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: var(--gap); }\n"
        ".card { background: var(--surface); padding: 20px; border-radius: var(--radius); box-shadow: 0 14px 30px rgba(15,23,42,0.08); }\n"
        ".card h3 { margin: 0 0 6px; font-family: var(--display-font); }\n"
        ".split { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: var(--gap); }\n"
        ".panel { background: var(--surface); padding: 28px; border-radius: var(--radius); }\n"
        ".panel.accent { border: 1px solid rgba(14,165,233,0.35); background: rgba(14,165,233,0.08); }\n"
        "@media (max-width: 768px) { .hero h1 { font-size: 36px; } .app { padding: 32px 5vw 60px; } }\n"
    )


def _render_workbench_styles() -> str:
    return (
        ".workbench { min-height: 100vh; background: var(--bg); color: var(--text); }\n"
        ".wb-top { display: flex; justify-content: space-between; align-items: center; padding: 18px 28px; border-bottom: 1px solid rgba(15,23,42,0.08); background: var(--surface); }\n"
        ".brand { font-family: var(--display-font); font-size: 20px; }\n"
        ".status { padding: 6px 12px; border-radius: 999px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; }\n"
        ".status.running { background: rgba(14,165,233,0.15); color: var(--primary); }\n"
        ".status.idle { background: rgba(15,23,42,0.08); color: #334155; }\n"
        ".wb-body { display: grid; grid-template-columns: 260px 1fr 320px; gap: 18px; padding: 18px 24px 32px; }\n"
        ".wb-left, .wb-right, .wb-center { background: var(--surface); border-radius: var(--radius); padding: 18px; box-shadow: 0 10px 24px rgba(15,23,42,0.08); }\n"
        ".panel-title { font-weight: 600; margin-bottom: 12px; text-transform: uppercase; font-size: 11px; letter-spacing: 0.12em; color: rgba(15,23,42,0.6); }\n"
        ".task-tree ul { list-style: none; padding: 0; margin: 0; display: grid; gap: 10px; }\n"
        ".task-tree li { display: flex; align-items: center; gap: 8px; font-weight: 500; }\n"
        ".dot { width: 8px; height: 8px; border-radius: 999px; background: var(--accent); }\n"
        "textarea { width: 100%; min-height: 160px; border-radius: 16px; border: 1px solid rgba(15,23,42,0.1); padding: 14px; font-family: var(--body-font); }\n"
        ".actions { display: flex; gap: 10px; margin: 12px 0 18px; }\n"
        ".tool-list, .event-stream { display: grid; gap: 12px; max-height: 320px; overflow: auto; }\n"
        ".tool-call, .event { padding: 12px; border-radius: 12px; background: rgba(15,23,42,0.04); }\n"
        ".tool-name { font-weight: 600; margin-bottom: 6px; }\n"
        ".tool-args { font-size: 12px; opacity: 0.8; }\n"
        ".event-type { font-weight: 600; margin-bottom: 6px; }\n"
        ".event pre { margin: 0; font-size: 11px; white-space: pre-wrap; word-break: break-word; }\n"
        ".preview-controls { display: flex; gap: 8px; margin-bottom: 8px; flex-wrap: wrap; }\n"
        ".preview-input { flex: 1; min-width: 140px; padding: 6px 10px; border-radius: 10px; border: 1px solid rgba(15,23,42,0.1); }\n"
        ".preview { height: 280px; border-radius: 12px; overflow: hidden; border: 1px solid rgba(15,23,42,0.1); margin-bottom: 12px; }\n"
        ".preview iframe { width: 100%; height: 100%; border: 0; }\n"
        ".editor-shell { display: grid; grid-template-columns: 180px 1fr; gap: 12px; }\n"
        ".file-tree { display: grid; gap: 6px; }\n"
        ".file-search { padding: 8px 10px; border-radius: 10px; border: 1px solid rgba(15,23,42,0.1); }\n"
        ".file-item { text-align: left; padding: 8px 10px; border-radius: 10px; border: 1px solid transparent; background: rgba(14,165,233,0.08); cursor: pointer; font-size: 12px; }\n"
        ".file-item.active { border-color: rgba(14,165,233,0.4); background: rgba(14,165,233,0.18); }\n"
        ".editor-pane { border-radius: 14px; overflow: hidden; border: 1px solid rgba(15,23,42,0.1); }\n"
        ".editor-header { padding: 8px 12px; font-size: 12px; background: rgba(15,23,42,0.06); }\n"
        ".diff-view { margin: 0; height: 360px; overflow: auto; background: #0f172a; color: #e2e8f0; padding: 12px; font-size: 12px; }\n"
        ".workspace-input { display: flex; gap: 10px; margin-bottom: 12px; }\n"
        ".workspace-input input { flex: 1; padding: 10px 12px; border-radius: 10px; border: 1px solid rgba(15,23,42,0.1); }\n"
        ".empty { font-size: 12px; opacity: 0.6; }\n"
        "@media (max-width: 1100px) { .wb-body { grid-template-columns: 1fr; } }\n"
    )

